### ISSUE TITLE
Android: Method 'AiForms.Renderers.PickerCell.set_ItemsSource' not found.

### ISSUE THREAD

**Issue by matteopiccioni** [muak/AiForms.Renderers#22]
Hello, 
I have the problem only with android and only in version 0.2.1 (0.1.0 was ok)

I need to calculate the ItemSource of PickerCell on page load and it can be empty sometimes. But if the ItemSource binding variable is empty, the SettingsView return me this error:
**System.ArgumentException
ItemsSource must have items more than or equal 1.**

For this way I decide to remove ItemSource="{Binding xxx}" from my xaml:
```
            <sv:PickerCell x:Name="pickIn3" SelectedCommand="{Binding SetColoreValueTextCommandPickIn3}" ValueTextColor="{Binding DefaultColorPickIn3}" 
                    Title="Aree"  DisplayMember="Etichetta" MaxSelectedNumber="{Binding BackupSelected_IN_AreeItems.Count}" 
            SelectedItems="{Binding BackupSelected_IN_AreeItems}" KeepSelectedUntilBack="true" PageTitle="Seleziona"  />
```

 and add it programmatically after (and only) the binding variable is filled with items.
```
            InitializeComponent();
            ...
            if (ViewModel.Lst_IN_AreeItems.Count > 0)
                pickIn3.ItemsSource = ViewModel.Lst_IN_AreeItems;
```
In iOS (0.1.0 and 0.2.1) and Android (0.1.0 and 0.2.0-pre2) it works, but in Android 0.2.0-pre3 and 0.2.1  it give me the error:
**System.MissingMethodException
Method 'AiForms.Renderers.PickerCell.set_ItemsSource' not found.**

Thanks for your support

**Comment by muak** [comment]
@matteopiccioni 

Hello.
Thank you for reporting the issue.

Though I tried testing similar code, I could not reproduce it.

In version 0.2.1, ItemsSource property allows you to set an empty collection.
So that message "ItemsSource must have..." cannot be displayed by now.

Thinking over that, this issue might attribute to caches in obj and bin folder.

Can you try it again after you delete obj and bin folder in each project and uninstall your app on device or simulator?

**Comment by matteopiccioni** [comment]
oh! you are right! after cleaning bin, obj, etc etc... no more 'ItemsSource must have items more than or equal 1.'
Thank you!

**Comment by muak** [comment]
@matteopiccioni 
It was good!
I'm glad that you solved that problem.

Thank you.
